/**
 * Voxnote service worker (generated by Serwist at build time into public/sw.js).
 *
 * Precaches the static app shell (HTML/JS/CSS/_next assets) so the UI loads with no
 * network after the first visit. The Whisper model weights are cached separately by
 * transformers.js (Cache API/IndexedDB), so transcription also works offline.
 *
 * This is a static-export SPA (no SSR/RSC routes), so we intentionally avoid Serwist's
 * `defaultCache` runtime strategies (which target dynamic server routes) and only do
 * precaching + a simple stale-while-revalidate for cross-origin assets like fonts.
 */

import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { Serwist, CacheFirst } from "serwist";

declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    // Precache manifest injected by Serwist at build time.
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  runtimeCaching: [
    {
      // Cache cross-origin fonts (Google Fonts) so the UI is consistent offline.
      matcher: ({ url }) => url.origin === "https://fonts.googleapis.com" || url.origin === "https://fonts.gstatic.com",
      handler: new CacheFirst({
        cacheName: "voxnote-fonts",
      }),
    },
  ],
  navigationPreload: false,
});

serwist.addEventListeners();
